"""
Model behaviour: capacity, optimistic locking, waitlist, constraints.
"""

from datetime import datetime, timedelta

import pytest
from sqlalchemy.exc import IntegrityError

from app.extensions import db
from app.models import Event, Registration
from app.models.event import WAITLIST_LIMIT
from app.models.registration import RegistrationStatus


class TestCapacity:
    def test_increment_until_full(self, make_event):
        event = make_event(capacity=2)
        assert event.increment_registration() is True
        assert event.increment_registration() is True
        assert event.is_full
        assert event.increment_registration() is False

    def test_increment_bumps_version(self, make_event):
        event = make_event(capacity=3)
        v0 = event.version
        event.increment_registration()
        assert event.version == v0 + 1

    def test_decrement_frees_a_spot(self, make_event):
        event = make_event(capacity=1)
        assert event.increment_registration() is True
        assert event.is_full
        event.decrement_registration()
        assert not event.is_full
        assert event.spots_left == 1

    def test_spots_left(self, make_event):
        event = make_event(capacity=5)
        event.increment_registration()
        assert event.spots_left == 4


class TestWaitlist:
    def test_can_join_waitlist_only_when_full(self, make_event, make_registration):
        event = make_event(capacity=1)
        assert not event.can_join_waitlist
        event.increment_registration()
        assert event.can_join_waitlist

    def test_waitlist_limit(self, make_event, make_registration):
        event = make_event(capacity=1)
        event.increment_registration()
        for i in range(WAITLIST_LIMIT):
            make_registration(event, email=f'wait{i}@example.com',
                              status=RegistrationStatus.WAITLIST)
        assert event.waitlist_count == WAITLIST_LIMIT
        assert not event.can_join_waitlist

    def test_promote_from_waitlist(self, make_event, make_registration):
        event = make_event(capacity=2)
        event.increment_registration()
        reg = make_registration(event, status=RegistrationStatus.WAITLIST)
        reg.promote_from_waitlist()
        db.session.commit()
        assert reg.status == RegistrationStatus.PENDING
        assert event.registered_count == 2


class TestRegistrationModel:
    def test_unique_email_per_event(self, make_event, make_registration):
        event = make_event()
        make_registration(event, email='dup@example.com')
        with pytest.raises(IntegrityError):
            make_registration(event, email='dup@example.com')
        db.session.rollback()

    def test_same_email_across_events_is_fine(self, make_event, make_registration):
        e1, e2 = make_event(), make_event(title='Second Course')
        make_registration(e1, email='both@example.com')
        make_registration(e2, email='both@example.com')
        assert Registration.query.filter_by(email='both@example.com').count() == 2

    def test_confirm_sets_timestamp(self, make_event, make_registration):
        reg = make_registration(make_event())
        assert reg.confirmed_at is None
        reg.confirm()
        assert reg.is_confirmed
        assert reg.confirmed_at is not None

    def test_cancel_decrements_event_count(self, make_event, make_registration):
        event = make_event(capacity=3)
        event.increment_registration()
        reg = make_registration(event)
        reg.cancel(reason='Test cancellation')
        assert reg.is_cancelled
        assert event.registered_count == 0

    def test_token_generation_unique(self, app):
        tokens = {Registration.generate_token() for _ in range(50)}
        assert len(tokens) == 50


class TestTimedRegistration:
    def test_not_yet_open(self, make_event):
        event = make_event(registration_opens_at=datetime.now() + timedelta(days=1))
        assert event.registration_not_yet_open
        assert not event.can_register

    def test_open_after_opens_at(self, make_event):
        event = make_event(registration_opens_at=datetime.now() - timedelta(hours=1))
        assert not event.registration_not_yet_open
        assert event.can_register

    def test_past_event_cannot_register(self, make_event):
        event = make_event(event_date=datetime.now() - timedelta(days=1))
        assert event.is_past
        assert not event.can_register


class TestEventDisplay:
    def test_slug_autogenerated(self, make_event):
        event = make_event(title='Shade & Texture Masterclass')
        assert event.slug == 'shade-texture-masterclass'

    def test_formatted_price(self, make_event):
        assert make_event(price=25000).formatted_price == '25 000 €'          # default currency EUR
        assert make_event(title='CZK', price=25000, currency='CZK').formatted_price == '25 000 Kč'
        assert make_event(title='VAT', price=469, price_includes_vat=True).formatted_price == '469 € incl. VAT'
        assert make_event(title='Free', price=None).formatted_price == 'On request'

    def test_test_event_exists(self, app):
        # create_app ensures the permanent test event
        assert Event.query.filter_by(is_test=True).count() == 1
