"""initial schema

Revision ID: d75191cd781c
Revises: 
Create Date: 2026-07-12 17:01:11.333913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75191cd781c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_user_email'), ['user_email'], unique=False)

    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('client_notification_emails', sa.String(length=500), nullable=True),
    sa.Column('doctor_notification_emails', sa.String(length=500), nullable=True),
    sa.Column('is_configured', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registered_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_note', sa.String(length=100), nullable=True),
    sa.Column('payment_bank_account', sa.String(length=50), nullable=True),
    sa.Column('payment_variable_symbol', sa.String(length=20), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_due_days', sa.Integer(), nullable=True),
    sa.Column('payment_instructions', sa.Text(), nullable=True),
    sa.Column('payment_qr_image', sa.String(length=500), nullable=True),
    sa.Column('lecturers', sa.Text(), nullable=True),
    sa.Column('program', sa.Text(), nullable=True),
    sa.Column('what_you_learn', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('includes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('body_image_url', sa.String(length=500), nullable=True),
    sa.Column('image_position_y', sa.Integer(), nullable=True),
    sa.Column('external_registration_url', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_category', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.Column('registration_open', sa.Boolean(), nullable=True),
    sa.Column('registration_opens_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_test'), ['is_test'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=True)

    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BOOK_ORDER', 'BOOK_NOTIFY', 'CONTACT', name='inquirytype'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), nullable=False),
    sa.Column('gdpr_consent_date', sa.DateTime(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_handled'), ['handled'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_type'), ['type'], unique=False)
        batch_op.create_index('ix_inquiries_type_email', ['type', 'email'], unique=False)

    op.create_table('spam_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('submitted_email', sa.String(length=255), nullable=True),
    sa.Column('submitted_name', sa.String(length=200), nullable=True),
    sa.Column('submitted_data', sa.Text(), nullable=True),
    sa.Column('event_slug', sa.String(length=200), nullable=True),
    sa.Column('time_on_page', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spam_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spam_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spam_logs_form_type'), ['form_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_spam_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_spam_logs_reason'), ['reason'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), nullable=False),
    sa.Column('gdpr_consent_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'WAITLIST', name='registrationstatus'), nullable=False),
    sa.Column('confirmation_token', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('confirmation_email_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_email_sent', sa.Boolean(), nullable=True),
    sa.Column('payment_email_sent', sa.Boolean(), nullable=True),
    sa.Column('payment_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('custom_email_sent', sa.Boolean(), nullable=True),
    sa.Column('custom_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_note', sa.String(length=500), nullable=True),
    sa.Column('variable_symbol', sa.String(length=20), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'email', name='uq_registration_event_email')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_confirmation_token'), ['confirmation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_registrations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_status'), ['status'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('smtp_response', sa.String(length=500), nullable=True),
    sa.Column('smtp_debug', sa.Text(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_email_type'), ['email_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_to_email'), ['to_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_to_email'))
        batch_op.drop_index(batch_op.f('ix_email_logs_status'))
        batch_op.drop_index(batch_op.f('ix_email_logs_email_type'))
        batch_op.drop_index(batch_op.f('ix_email_logs_created_at'))

    op.drop_table('email_logs')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_registrations_payment_status'))
        batch_op.drop_index(batch_op.f('ix_registrations_event_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_email'))
        batch_op.drop_index(batch_op.f('ix_registrations_confirmation_token'))

    op.drop_table('registrations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('spam_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spam_logs_reason'))
        batch_op.drop_index(batch_op.f('ix_spam_logs_ip_address'))
        batch_op.drop_index(batch_op.f('ix_spam_logs_form_type'))
        batch_op.drop_index(batch_op.f('ix_spam_logs_created_at'))

    op.drop_table('spam_logs')
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index('ix_inquiries_type_email')
        batch_op.drop_index(batch_op.f('ix_inquiries_type'))
        batch_op.drop_index(batch_op.f('ix_inquiries_handled'))
        batch_op.drop_index(batch_op.f('ix_inquiries_email'))
        batch_op.drop_index(batch_op.f('ix_inquiries_created_at'))

    op.drop_table('inquiries')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_slug'))
        batch_op.drop_index(batch_op.f('ix_events_is_test'))
        batch_op.drop_index(batch_op.f('ix_events_is_active'))

    op.drop_table('events')
    op.drop_table('email_settings')
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_logs_user_email'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_target_type'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_action'))

    op.drop_table('admin_logs')
    # ### end Alembic commands ###
